server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 121.40.241.29:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item/**,/items/**
        - id: search-service
          uri: lb://item-service
          predicates:
            - Path=/search/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: address-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
      default-filters:
        - AddResponseHeader=truth,anyone long-press like button will be rich
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
