server:
  port: 8081
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.heima.item.controller
  db:
    database: hm-item
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀
# Seata配置
seata:
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group